services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./App:/front-app
      - /front-app/node_modules
    # command: ["npx", "ng", "serve", "--host=0.0.0.0", "--port=5005"]
